# Generated by Django 3.1.5 on 2021-03-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('surname', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
